SOLVER:
  MAX_ITER: 600000
  CHECKPOINT_PERIOD: 100000
  WEIGHT_DECAY: 0.00005 # 0.000484
  WEIGHT_DECAY_BIAS: 0.00005 # 0.0
  MOMENTUM: 0.937
  BASE_LR: 0.01
  IMS_PER_BATCH: 64
  LR_SCHEDULER_NAME: WarmupCosineLR