SOLVER:
  MAX_ITER: 600000
  CHECKPOINT_PERIOD: 100000
  WEIGHT_DECAY: 0.00005
  WEIGHT_DECAY_BIAS: 0.00005
  BASE_LR: 0.01
  IMS_PER_BATCH: 8
  LR_SCHEDULER_NAME: WarmupCosineLR

DATALOADER:
  NUM_WORKERS: 5